name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    name: Codeception Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run composer
        uses: php-actions/composer@v1
      - name: phpmd
        run: vendor/bin/phpmd ./src text phpmd-ruleset.xml
      - name: Run codeception tests
        run: vendor/bin/codecept run
