name: CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer install
        uses: php-actions/composer@v1
      - name: Run codeception tests
        run: vendor/bin/codecept run

  quality:
    name: Code quality
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer install
        uses: php-actions/composer@v1
      - name: phpmd
        run: vendor/bin/phpmd ./src text phpmd-ruleset.xml
      - name: phpcs
        run: vendor/bin/phpcs --standard=PSR12 ./src/
