name: Mess Detector

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  phpmd:
    name: PHPMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Composer install
        uses: php-actions/composer@v1
      - name: phpmd
        run: vendor/bin/phpmd ./src text phpmd-ruleset.xml
